# Generated by Django 3.1.6 on 2021-08-19 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausername', models.TextField(default='')),
                ('apassword', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llocation', models.TextField(default='')),
                ('laddress', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vname', models.TextField(default='')),
                ('vage', models.TextField(default='')),
                ('vcnumber', models.TextField(default='')),
                ('vemail', models.TextField(default='')),
                ('vusername', models.TextField(default='')),
                ('vpassword', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocation', models.TextField(default='')),
                ('bdate', models.TextField(default='')),
                ('bdate2', models.TextField(default='')),
                ('bpeople', models.TextField(default='')),
                ('brates', models.TextField(default='')),
                ('visitor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ownlist.visitor')),
            ],
        ),
    ]
