# Generated by Django 3.1.6 on 2021-05-01 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npet', models.TextField(default='')),
                ('nname', models.TextField(default='')),
                ('nAddress', models.TextField(default='')),
                ('nBreed', models.TextField(default='')),
                ('nDay', models.TextField(default='')),
                ('list', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='ownlist.list')),
            ],
        ),
    ]
